
/*im
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import project.connectionprovider;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils; 
/*
/**
 *
 * @author HP
 */
public class waterusagerecord extends javax.swing.JFrame {
         public int flag=0;
    /**
     * Creates new form waterusagerecord
     */
    public waterusagerecord() {
        initComponents();
        jLabel2.setVisible(false);
        jLabel5.setVisible(false);
        jTextField4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(330, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("block number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 99, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 250, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 730, 58));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Block Number does not exist!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 200, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("water used date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("used amount");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 104, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 250, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("problem");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 100, 30));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 250, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("aditional water required");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("does water quality decrese");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 184, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jButton2.setText("close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        jButton3.setText("save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setText("yes");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 85, -1));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox2.setText("yes");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 85, -1));

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox3.setText("yes");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, 70));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("is their any other problem");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient background.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox3.isSelected()){
        jLabel5.setVisible(true);
        jTextField4.setVisible(true);}
        else{
            jLabel5.setVisible(false);
        jTextField4.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String blocknumber=jTextField1.getText();
        try{
        Connection con=connectionprovider.getCon();
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery("select *from block where blocknumber='"+blocknumber+"'");
     jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    
    if (!rs.next()) {
        flag=0; 
    } else{
       flag=1; 
    }
       ResultSet bData = st.executeQuery("SELECT wateramount, waterclarity FROM block WHERE blocknumber = '" + blocknumber + "'");
    
    // Check if ResultSet contains data
    if (bData.next()) {
        float waterAmount = bData.getFloat("wateramount");
        float waterClarity = bData.getFloat("waterclarity");
        
        // Show message if water amount is less than 3000
        if (waterAmount < 3000) {
            JOptionPane.showMessageDialog(null, "Shortage of water in the block.");
        }
        
        // Show message if water clarity is not within the range of 5 to 8
        if (waterClarity < 5 || waterClarity > 8) {
            JOptionPane.showMessageDialog(null, "Water is not pure in the block.");
        }
    } else {
        // ResultSet is empty, handle accordingly
        JOptionPane.showMessageDialog(null, "No data found for the block.");
        return;
    } }
catch(Exception e){
      e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Connection Error");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String blocknumber = jTextField1.getText();

    // Check if the block number exists in the database
    try {
        Connection con = connectionprovider.getCon();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM block WHERE blocknumber='" + blocknumber + "'");
        
        // If the block number doesn't exist, show a message and exit the method
        if (!rs.next()) {
            JOptionPane.showMessageDialog(null, "Block number does not exist");
            return;
        }
       
            
            else 
        {
            
         
        String dateofwaterused = jTextField2.getText(); // Get the date string from the text field
         if (dateofwaterused.isEmpty()||blocknumber.isEmpty() ) {
        JOptionPane.showMessageDialog(null, "Please enter all necessary data");
        return; // Exit the method
    }
        String aditionalwaterrequired;
        if(jCheckBox1.isSelected()){
        aditionalwaterrequired="yes";
        }
        else{
        aditionalwaterrequired="no";
          }

        String  waterqualitydecrese;
        if(jCheckBox2.isSelected()){
       waterqualitydecrese="yes";
        }
        else{
         waterqualitydecrese="no";
          }
          String problem;
         String   otherproblem;
        if(jCheckBox3.isSelected()){
        otherproblem="yes";
             problem=jTextField4.getText();
             if (problem.isEmpty() ) {
        JOptionPane.showMessageDialog(null, "Please enter all necessary data");
        return; // Exit the method
    }
        }
        else{
          otherproblem="no";
          problem="no problem";
          }
        float amountofwaterused = 0.0f; // Default value in case of parsing error
try {
    amountofwaterused = Float.parseFloat(jTextField3.getText());
} catch (NumberFormatException e) {
    // Handle parsing error
   JOptionPane.showMessageDialog(null, "Please enter only numbers in the this field");
   return;
}
try{
       ResultSet blockData = st.executeQuery("SELECT wateramount FROM block WHERE blocknumber = '" + blocknumber + "'");
                float currentWaterAmount = 0;

                if (blockData.next()) {
                    currentWaterAmount = blockData.getFloat("wateramount");
                }

                // Calculate the new water amount
                float newWaterAmount = currentWaterAmount - amountofwaterused;

                // Check if there is enough water in the block
                if (newWaterAmount < 0) {
                    JOptionPane.showMessageDialog(null, "Insufficient water in the block.");
                } else {
                    // Update the water amount in the block table
                    st.executeUpdate("UPDATE block SET wateramount = '" + newWaterAmount + "' WHERE blocknumber = '" + blocknumber + "'");
ResultSet checkResultSet = st.executeQuery("SELECT * FROM data WHERE blocknumber = '" + blocknumber + "'");
    
                    // Insert data into the data table
                     if (checkResultSet.next()) {
        st.executeUpdate("UPDATE data SET dateofwaterused = '" + dateofwaterused + "', amountofwaterused = '" + amountofwaterused + "', aditionalwaterrequired = '" + aditionalwaterrequired + "', waterqualitydecrese = '" + waterqualitydecrese + "', otherproblem = '" + otherproblem + "', problem = '" + problem + "' WHERE blocknumber = '" + blocknumber + "'");
        JOptionPane.showMessageDialog(null, "Data updated successfully.");
    } else {
                    st.executeUpdate("INSERT INTO data VALUES ('" + blocknumber + "','" + dateofwaterused + "','" + amountofwaterused + "','" + aditionalwaterrequired + "','" + waterqualitydecrese + "','" + otherproblem + "','" + problem + "')");

                    JOptionPane.showMessageDialog(null, "Water amount updated successfully.");
                    JOptionPane.showMessageDialog(null, "Data successfully updated.");
                     }
                    
                }
      
    // If the block number exists in the data table, update the existing row
   
        // If the block number doesn't exist in the data table, insert a new row
        st.executeUpdate("INSERT INTO data VALUES ('" + blocknumber + "','" + dateofwaterused + "','" + amountofwaterused + "','" + aditionalwaterrequired + "','" + waterqualitydecrese + "','" + otherproblem + "','" + problem + "')");
        JOptionPane.showMessageDialog(null, "Data inserted successfully.");
    
      JOptionPane.showMessageDialog(null,"succesfully updates");
    
    
    
   
}catch(Exception e){
    JOptionPane.showMessageDialog(null,"succesfully updates");
    }
        }
        setVisible(false);
      new waterusagerecord().setVisible(true);
    }
       catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Connection Error");
        return;
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(waterusagerecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(waterusagerecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(waterusagerecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(waterusagerecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new waterusagerecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
